version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "81:80"
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: app
        depends_on:
            - db

    db:
        image: mysql:8.0.30
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: docker_db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8101:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: db
